# Generated by Django 4.0.3 on 2022-05-06 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Startup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
                ('initial_capital', models.IntegerField()),
                ('accumulated_capital', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('category', models.CharField(choices=[('IT', 'IT'), ('Ecology', 'Ecology'), ('Electronic', 'Electronic'), ('Health', 'Health'), ('Education', 'Education'), ('Gaming', 'Gaming'), ('Small Business', 'Small Business'), ('Other', 'Other')], default='Other', max_length=20)),
                ('startupper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.userstartupper')),
            ],
        ),
        migrations.CreateModel(
            name='Investing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investment_amount', models.IntegerField()),
                ('investment_date', models.DateTimeField(auto_now_add=True)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.userinvestor')),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startup.startup')),
            ],
        ),
    ]
