# Generated by Django 4.0.3 on 2022-04-27 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_delete_investor_delete_startupper'),
        ('startup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investment_amount', models.IntegerField()),
                ('investment_date', models.DateTimeField(auto_now_add=True)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.userinvestor')),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startup.startup')),
            ],
        ),
    ]
