# Generated by Django 4.0.3 on 2022-04-10 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0006_startups'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Startup',
        ),
    ]
