# Generated by Django 4.0.3 on 2022-04-10 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_userinvestor_current_money'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Investor',
        ),
        migrations.DeleteModel(
            name='Startupper',
        ),
    ]
